# Generated by Django 3.2 on 2021-04-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='year',
        ),
    ]
