# Generated by Django 3.2 on 2021-04-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_join_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
