# Generated by Django 3.2 on 2021-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_image_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='status',
        ),
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
