# Generated by Django 3.2 on 2021-04-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20210418_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='company/')),
            ],
        ),
    ]
