# Generated by Django 3.2 on 2021-04-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_cooperate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='activity/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
