# Generated by Django 3.2 on 2021-04-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='date',
        ),
    ]
