# Generated by Django 3.2 on 2021-04-25 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='date',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
