# Generated by Django 3.2 on 2021-04-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
