# Generated by Django 3.2 on 2021-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link_QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
